runs:
  using: composite

  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm

    - name: Install dependencies
      run: npm ci
      shell: bash # Composite jobs must specify the shell.

    # @template-customization-start

    - name: Setup Python 3
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
        cache: pip

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
      shell: bash # Composite jobs must specify the shell.

    # @template-customization-end
