runs:
  using: composite

  steps:
    - name: Enable corepack to work around a setup-node bug
      run: corepack enable
      shell: bash # Composite jobs must specify the shell.

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: yarn

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash # Composite jobs must specify the shell.

    # @template-customization-start

    - name: Setup Python 3
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
        cache: pip

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./image-generator/requirements.txt
      shell: bash # Composite jobs must specify the shell.

    # @template-customization-end
